version: "3.3"
services:
  website:
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
    volumes:
      - ./website:/var/www/html
    ports:
      - 80:80
    networks:
      - pozos_network
    depends_on:
      - api
  api:
    build: "./simple_api"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    ports:
      - 5000:5000
    networks:
      - pozos_network

networks:
  pozos_network:
